### PR TITLE
update doc with Svelte 4 generics

### PR DESCRIPTION
**Pull request by Skylli202**
#22

### CODE REVIEW

**Comment by Skylli202** [comment]
I think you might want to update the text who explain the advanced typing going on in this example. I'm afraid that I am not skilled enough to fully understand your solution.

**Comment by ciscoheat** [comment]
Thank you, I will use a tab to show both versions, so I will use this as inspiration and close it when updated!

**Comment by ciscoheat** [comment]
Docs updated on the [components](https://superforms.rocks/components#using-a-formfieldproxy) page now.

**Comment by Skylli202** [comment]
Awesome!

**Pull request closed without merging**
